export const recipes = {
    recipes: [
        {
            title: "Croatian Stuffed Peppers Recipe",
            picture: {
                title: "Punjene-Paprike",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/3iTI3z2kCQcJ1uDC2XoGn3/a119a6bcbe8e71864b9cbf65322f2133/punjene-paprike.jpg",
                    details: {
                        size: 160786,
                        image: {
                            width: 1920,
                            height: 1080,
                        },
                    },
                    fileName: "punjene-paprike.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "The Peppers & Stuffing Flour",
                "8-10 medium-sized peppers",
                "Milk",
                "1 kg of minced meat. Soft Butter",
                "Pinch of salt Brown Sugar",
                "Cracked pepper to taste White Sugar",
                "1 tablespoon of smoked ground paprika Cinnamon",
                "1 tablespoon of hot ground paprika",
                "Vanilla Sugar",
                "1 tablespoon of mixed dried herbs (optional) Yeast",
                "1 cup of uncooked rice Salt",
                "1 egg",
                "2 tablespoons of soda water or a pinch of bicarbonate soda",
                "2 large cloves of chopped fresh garlic",
                "1/2 cup of freshly chopped parsley",
                "200 grams finely diced speck (7 oz) You can cut this back if you do not like too much of a smokey flavor",
                "The Sauce",
                "14 tablespoons olive oil",
                "1 finely diced medium onion",
                "2 tablespoons all-purpose flour",
                "2 tablespoons tomato paste",
            ],
            servings: 8,
            calories: 209,
            difficulty: "hard",
            time: "1:00",
            course: "main",
            steps:
                "The Peppers & Stuffing\n1. Take 8-10 medium-sized peppers, and carefully cut out the top and set aside the as you'll use this as a lid for the pepper later. Scoop out the insides and be sure to remove all of the seeds and any stringy pieces. Wash the lids and peppers and allow them to dry upside down on paper towel while you make the stuffing\n2. To make the stuffing, add all the ingredients to a large bowl and use your hands to lightly mix until combined. Make sure the bowl is big enough for you to be able to use your hands to mix it well without spilling it all over the floor (trust me, it happens)\n3. Flip the peppers over and fill them with the stuffing until they are almost full. But do not overfill them. The rice expands during cooking and they'll burst leaving you a hideous mess in your saucepan. Leave the lids off for the moment\nThe Sauce\nIn a separate saucepan on medium heat add 4 tablespoons of olive oil and fry 1 finely diced medium onion\n6. Once onions are transparent, add in 2 tablespoons of flour and fry until light brown. Add into the pan 2 tablespoons of tomato paste, 2 litres of homemade stock (or water) along with a Pinch of Vegeta and add salt & pepper to your taste\n",
            id: "RJ8RcE1qEfMoNK9at1VOb",
        },
        {
            title: "Croatian Shopska Salad",
            picture: {
                title: "sopska salad",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/bQWwA516TSPGIwcBKcH7B/40769ae4c28fa5b368d14a2c8b7822a1/DSC_0173.jpg",
                    details: {
                        size: 256155,
                        image: {
                            width: 1102,
                            height: 715,
                        },
                    },
                    fileName: "DSC_0173.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "1 large beefsteak tomato",
                "3 mini cucumbers",
                "3 bell peppers",
                "1 medium onion",
                "1 handful fresh parsley",
                "3 tablespoons sunflower oil",
                "2 tablespoons red wine vinegar",
                "1 cup feta cheese",
                "fine sea salt and freshly ground black pepper",
            ],
            servings: 2,
            calories: 153,
            difficulty: "easy",
            time: "00:20",
            course: "salad",
            steps:
                "1. In a small bowl, combine the garlic, olive oil, molasses and crushed red pepper. Season the dressing with salt.\n2. In a large bowl, toss the tomatoes with the cucumbers, scallions, green bell pepper, onion, parsley and mint.\n3. Pour the dressing over the salad and toss well.\n4. Serve at once.",
            id: "4pjcfGbyaywSgPo00hElEf",
        },
        {
            title: "Swabian Potato Salad",
            picture: {
                title: "Potatosalad",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/7o8CrMayneINqpEQbLbsZw/db4c084dc69bfd4835986f5938cbf58b/PotatoSalad.jpg",
                    details: {
                        size: 175026,
                        image: {
                            width: 1280,
                            height: 800,
                        },
                    },
                    fileName: "PotatoSalad.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "900 g waxy potatoes",
                "1 vegetable onion",
                "100 ml vinegar",
                "130 ml rapeseed oil",
                "100 ml vegetable stock",
                "1 bunch of chives",
                "2 tbsp mustard",
                "Salt and white pepper",
            ],
            servings: 4,
            calories: 102,
            difficulty: "medium",
            time: "0:45",
            course: "salad",
            steps:
                "Boil the potatoes in their skins in a pan of water (this takes about 25 minutes). In the meantime, peel the onions and cut them into small cubes. Wash the chives and cut them into very fine rings. Bring the vegetable stock to the boil once and set aside.\nTip: If the sharpness of the onion is too intense for you, you can wrap the chopped onion cubes in a tea towel and rinse with cold water. Or sauté the onion cubes in rapeseed oil for a few minutes until they are translucent.\nNow you can peel the potatoes (preferably when they are still slightly warm) and cut them into slices or, if you like it particularly fine, grate the potatoes into slices. Next, add the vinegar, finely diced onion, salt, mustard, pepper and warm stock and carefully fold into the potatoes. Then drizzle in the rapeseed oil while stirring gently. The vinegar, spices and oil will gradually combine to create a perfect salad dressing that nestles around the potato slices.\nNow sprinkle the finely chopped chives over the potato salad and serve the salad in bowls or deep plates. The potato salad can be part of a salad buffet or serve as a side dish with meatballs or sausages.",
            id: "5JG62BIVlRHVwOezhdPRMt",
        },
        {
            title: "Labskaus",
            picture: {
                title: "Labskaus",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/biIvJlYKrDIHo94pm40a5/aab96220989f73169d88c31c94664b01/Labskaus-1024x612.jpg",
                    details: {
                        size: 116311,
                        image: {
                            width: 1024,
                            height: 612,
                        },
                    },
                    fileName: "Labskaus-1024x612.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "340 g Canned Corned Beef",
                "1 kg  Potatoes",
                "500 g Pickled Red Beet",
                "2 Bay Leaves",
                "3 Onions",
                "4 Gherkins",
                "2 tbsp Liquid from the Gherkins",
                "some Rapeseed Oil and Salt and Pepper",
                "1 Pinch Ground Cloves",
                "4 Eggs",
                "4 Matjes Fillets",
            ],
            servings: 2,
            calories: 256,
            difficulty: "easy",
            time: "1:15",
            course: "main",
            steps:
                "Cook the peeled and chopped potatoes with the bay leaves in salted water.\nSauté the finely diced onions in oil for about 10 minutes over a medium heat, add the corned beef, cut into pieces and heat through. Dice half of the pickled beet and sauté, then pour in a little cucumber liquid. Leave everything to simmer for 5 minutes.\nHeat the vegetable stock in a separate pan and add the cooked potatoes. Roughly mash everything into mashed potatoes. Then stir in the meat, beetroot and onion mixture, season everything with the spices and keep warm.\nNow fry the four eggs.\nTo serve, arrange the Labskaus mash with a fried egg, a matjes fillet, some beetroot and gherkins.\n",
            id: "5tuMVKTw09MZt86MDUdRuL",
        },
        {
            title: "Grünkohl mit Pinkel",
            picture: {
                title: "Grünkohl",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/52xCDdD3GlHF3WnKW9Tbzb/39924abfb2161a8694668e476048da43/Fotolia_58142444_M.jpg",
                    details: {
                        size: 738669,
                        image: {
                            width: 1687,
                            height: 1126,
                        },
                    },
                    fileName: "Fotolia_58142444_M.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "2.5 kg Kale",
                "1 Onion",
                "100 g Smoked Pancetta",
                "2 tbsp Lard",
                "250 g Pork Belly Meat",
                "500 ml Vegetable Stock",
                "5 Pinkel Sausages",
                "1 tsp Mustard",
            ],
            servings: 4,
            calories: 402,
            difficulty: "easy",
            time: "1:30",
            course: "main",
            steps:
                "Remove the stems from the kale, wash and drain. Place the kale in a large pan of boiling salted water. Allow to collapse, drain in a sieve and then roughly chop.\nPeel and finely chop the onion. Dice the bacon. Heat the lard in a pan and sauté the onion until translucent. Add the bacon and pork belly and fry.\nAdd the kale and pour in approx. 300 ml vegetable stock. Place the pork belly between the kale and cook for approx. 1 hour. Add a little stock every now and then.\nAfter an hour's cooking time, put Pinkel sausage into the kale and mix the contents. Simmer for another 5 minutes, season with salt and mustard.\nRemove the pork belly, cut into pieces and serve with the kale and sausages. Serve with boiled potatoes and mustard.",
            id: "18TKgTNUhsORZse2ZPOiGT",
        },
        {
            title: "Gemüseeintopf mit Mettenden",
            picture: {
                title: "Gemüseeintopf",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/6jR6WRo7oQLHtdeGa8WhRT/b636ef8f79f4aac981240233c7704472/herbstlicher-gemueseeintopf-mit-wuerstchen-321272.jpg",
                    details: {
                        size: 538956,
                        image: {
                            width: 1170,
                            height: 460,
                        },
                    },
                    fileName: "herbstlicher-gemueseeintopf-mit-wuerstchen-321272.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "1 bunch Greens",
                "1 bunch Parsley",
                "1–2 Onions",
                "2 Bay Leaves",
                "600 g Potaoes",
                "500 g Carrots",
                "450 g Leek",
                "250 g Frozen or Canned Peas",
                "Salt/Pepper/Vegetable Stock Powder to tase",
                "1-2 Mettwurst (Sausages) per Person",
            ],
            servings: 4,
            calories: 345,
            difficulty: "easy",
            time: "1:20",
            course: "main",
            steps:
                "Clean, wash and roughly chop the soup greens. Pluck the parsley leaves, put the stalks to one side. Wash and cut the onions. Roast the onions in a large pan without fat.\nPour in 2 liters of water, add the greens, parsley stalks, bay leaves, 1 teaspoon of salt, some pepper. Bring to the boil, cover and simmer for approx. 30 minutes.\nPeel, wash and dice the potatoes. Wash, peel and slice the carrots. Clean and wash the leek and cut into rings. Chop the parsley.\nAdd the potato, carrots, leek and Mettwurst, cover and cook for approx. 15 minutes. Approx. 3 minutes before the end of the cooking time, add the frozen peas and simmer.\nAdd the parsley to the soup, except for a little for sprinkling, and season with salt and pepper. Sprinkle with the remaining parsley.\n",
            id: "29bGcyvddJvN51Nbg63J1X",
        },
        {
            title: "Franzbrötchen",
            picture: {
                title: "Franzbrötchen",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/6oC0csCbYvbfwJVUKp7Q4K/d69940d10ac16d0400dcaf5eaac1627b/kleiner-P1480787-768x432.jpg",
                    details: {
                        size: 73609,
                        image: {
                            width: 768,
                            height: 432,
                        },
                    },
                    fileName: "kleiner-P1480787-768x432.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "500 g Flour",
                "275 ml Milk",
                "200 g Soft Butter",
                "125 g Brown Sugar",
                "75 g White Sugar",
                "1 Tbs Cinnamon",
                "1 Packet Vanilla Sugar",
                "1/2 Cube Yeast",
                "Pinch of Salt",
            ],
            servings: 12,
            calories: 332,
            difficulty: "medium",
            time: "1:00",
            course: "dessert",
            steps:
                "Crumble ½ cube of yeast into a tall container & pour in 275 milliliters of lukewarm milk. Next, stir everything together with a whisk or fork until the yeast has completely dissolved.\nThen place the yeast-milk mixture together with 500 grams of flour, 100 grams of soft butter, 75 grams of sugar, 1 sachet of vanilla sugar & a pinch of salt in a mixing bowl & knead into a smooth dough for 4 - 5 minutes using a food processor or a mixer with dough hooks.\nThen shape the dough into a ball, place back in the mixing bowl & leave to rest covered with a kitchen towel for 30 - 45 minutes until the dough has visibly increased in volume.\nMix 125 grams of brown sugar with 1 heaped tablespoon of cinnamon & set aside. Line 2 baking trays with baking paper. After the resting time, place the dough on a lightly floured work surface & roll out with a rolling pin as thinly and rectangularly as possible to a size of 50cm x 40cm.\nBrush the rolled out dough with 100 grams of soft butter, then sprinkle evenly with the cinnamon & sugar mixture & roll up tightly from the long side. Cut the dough roll with a knife diagonally offset or trapezoidally into 12 rolls of approximately the same size.\nTo achieve the typical look, press the middle of each roll with a wooden spoon handle so that the cut surfaces to the left & right of the handle bulge slightly upwards. Place the finished buns on the 2 prepared baking trays with plenty of space between them & leave to rest covered with a kitchen towel for a further 30 - 45 minutes.\nPreheat the oven to 180°C (top/bottom heat) in good time & bake the French rolls for 15 - 20 minutes after the resting time until golden brown.\n",
            id: "1CIcWiHoVvAAIRnhG7YHEz",
        },
        {
            title: "Strudel",
            picture: {
                title: "Strudel",
                description: "",
                file: {
                    url: "//images.ctfassets.net/xa7obka5ntht/4sqVLPLhuFXG8sI3ZL1GEP/94b9d9eefc11b924e7b671a5fb0ed480/strudla.jpg",
                    details: {
                        size: 170312,
                        image: {
                            width: 1280,
                            height: 960,
                        },
                    },
                    fileName: "strudla.jpg",
                    contentType: "image/jpeg",
                },
            },
            ingredients: [
                "For the Strudel Dough Flour",
                "1/2 cup lukewarm water Milk",
                "1/2 teaspoon vinegar Soft Butter",
                "3/4 teaspoon salt Brown Sugar",
                "2 cups all-purpose flour plus more for surface White Sugar",
                "1 tablespoon cold unsalted butter Cinnamon",
                "For the Cherry Strudel Filling Vanilla Sugar",
                "8 cups sour cherries (stemmed and pitted) Yeast",
                "2 teaspoons grated lemon zest (optional) Salt",
                "1 1/2 to 2 cups sugar or to taste",
                "Melted butter",
                "3/4 cup ground walnuts",
                "1/2 cup chopped flat-leaf parsley",
                "Confectioners' sugar for garnish",
            ],
            servings: 2,
            calories: 179,
            difficulty: "medium",
            time: "1:00",
            course: "dessert",
            steps:
                "Make the Strudel Dough\n1. In a small bowl, mix 1/2 cup lukewarm water, 1/2 teaspoon vinegar and 3/4 teaspoon salt. Place 2 cups all-purpose flour in a large bowl and cut in 1 tablespoon cold butter in as for pie dough. Add water mixture and stir by hand for about 5 minutes or until dough becomes smooth.\n2. Transfer dough to a lightly floured surface and knead for about 5 minutes, adding as little extra flour as possible. Cover with plastic wrap and let rest 30 minutes.\nFill and Bake the Strudel\n1. Place rack in the middle of oven and heat to 400 F. Brush the stretched dough liberally with melted butter. Place the cherry filling along one long edge in a 3-inch-wide strip, 2 inches from the edges. Sprinkle ground walnuts over the filling.\n2. Place parchment on baking sheets and transfer strudel sections to them, seam-side down. Bake 10 minutes, reduce heat to 375 F and bake 20 to 25 minutes more or until strudel is crisp and golden.\n3. Remove from oven, cool slightly and then cut on an angle into slices. Dust with confectioners' sugar. You may also cool completely to make the slicing easier and then rewarm in a microwave. Dust with confectioners' sugar and serve as is or with a dollop of whipped cream or scoop of ice cream.",
            id: "77nl66G4MusYknhNQRcB4Z",
        },
    ]
};